[phases.setup]
nixPkgs = ['nodejs-20_x', 'npm']

[phases.install]
cmds = ['npm ci --production=false']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'

# Forzar Node.js 20, no Python
[providers]
node = true
python = false

[variables]
NODE_ENV = "production"
